/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Library.Objetos;
import java.awt.Color;

/**
 *
 * @author andre
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form Sistema
     */
    public Sistema() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Logo = new javax.swing.JLabel();
        jTabbedPanePrincipal = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_BuscarCliente = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPanelClientes = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel_imagenCliente = new javax.swing.JLabel();
        jLabel_id_Cliente = new javax.swing.JLabel();
        jTextField_idCliente = new javax.swing.JTextField();
        jLabel_nombreCliente = new javax.swing.JLabel();
        jTextField_nombreCliente = new javax.swing.JTextField();
        jTextField_apellidoCliente = new javax.swing.JTextField();
        jLabel_apellidoCliente = new javax.swing.JLabel();
        jTextField_telefonoCliente = new javax.swing.JTextField();
        jLabel_telefonoCliente = new javax.swing.JLabel();
        jTextField_direccionCliente = new javax.swing.JTextField();
        jLabel_direccionCliente = new javax.swing.JLabel();
        jButton_cancelarCliente = new javax.swing.JButton();
        jButton_agregarCliente = new javax.swing.JButton();
        jLabel_emailCliente = new javax.swing.JLabel();
        jTextField_emailCliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton_Cliente = new javax.swing.JButton();

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1510, 762));

        jPanel1.setBackground(new java.awt.Color(70, 106, 124));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Cooper Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sistema de punto de ventas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/1647917573945 (3).png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPanePrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanePrincipal.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1445, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );

        jTabbedPanePrincipal.addTab("Ventas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(70, 106, 124));
        jLabel3.setText("Clientes");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(70, 106, 124));
        jLabel4.setText("Buscar");

        jTextField_BuscarCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addGap(255, 255, 255)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(742, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jTextField_BuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTabbedPanelClientes.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanelClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(70, 106, 124));
        jLabel2.setText("Información del cliente");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_imagenCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel_imagenCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_imagenCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_imagenClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_imagenCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_imagenCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel_id_Cliente.setBackground(new java.awt.Color(70, 106, 124));
        jLabel_id_Cliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_id_Cliente.setForeground(new java.awt.Color(70, 106, 124));
        jLabel_id_Cliente.setText("ID Cliente:");

        jTextField_idCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_idCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_idClienteActionPerformed(evt);
            }
        });
        jTextField_idCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_idClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_idClienteKeyTyped(evt);
            }
        });

        jLabel_nombreCliente.setBackground(new java.awt.Color(70, 106, 124));
        jLabel_nombreCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_nombreCliente.setForeground(new java.awt.Color(70, 106, 124));
        jLabel_nombreCliente.setText("Nombre:");

        jTextField_nombreCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_nombreCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_nombreClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_nombreClienteKeyTyped(evt);
            }
        });

        jTextField_apellidoCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_apellidoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_apellidoClienteActionPerformed(evt);
            }
        });
        jTextField_apellidoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_apellidoClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_apellidoClienteKeyTyped(evt);
            }
        });

        jLabel_apellidoCliente.setBackground(new java.awt.Color(70, 106, 124));
        jLabel_apellidoCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_apellidoCliente.setForeground(new java.awt.Color(70, 106, 124));
        jLabel_apellidoCliente.setText("Apellido Paterno:");

        jTextField_telefonoCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_telefonoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_telefonoClienteActionPerformed(evt);
            }
        });
        jTextField_telefonoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_telefonoClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_telefonoClienteKeyTyped(evt);
            }
        });

        jLabel_telefonoCliente.setBackground(new java.awt.Color(70, 106, 124));
        jLabel_telefonoCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_telefonoCliente.setForeground(new java.awt.Color(70, 106, 124));
        jLabel_telefonoCliente.setText("Telefono:");

        jTextField_direccionCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_direccionCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_direccionClienteActionPerformed(evt);
            }
        });
        jTextField_direccionCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_direccionClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_direccionClienteKeyTyped(evt);
            }
        });

        jLabel_direccionCliente.setBackground(new java.awt.Color(70, 106, 124));
        jLabel_direccionCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_direccionCliente.setForeground(new java.awt.Color(70, 106, 124));
        jLabel_direccionCliente.setText("Dirección:");

        jButton_cancelarCliente.setBackground(new java.awt.Color(204, 204, 204));
        jButton_cancelarCliente.setForeground(new java.awt.Color(70, 106, 124));
        jButton_cancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/grupo (1).png"))); // NOI18N
        jButton_cancelarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_cancelarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelarClienteActionPerformed(evt);
            }
        });

        jButton_agregarCliente.setBackground(new java.awt.Color(204, 204, 204));
        jButton_agregarCliente.setForeground(new java.awt.Color(70, 106, 124));
        jButton_agregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/grupo (1).png"))); // NOI18N
        jButton_agregarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_agregarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_agregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_agregarClienteActionPerformed(evt);
            }
        });

        jLabel_emailCliente.setBackground(new java.awt.Color(70, 106, 124));
        jLabel_emailCliente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel_emailCliente.setForeground(new java.awt.Color(70, 106, 124));
        jLabel_emailCliente.setText("e-mail:");

        jTextField_emailCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField_emailCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_emailClienteActionPerformed(evt);
            }
        });
        jTextField_emailCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_emailClienteKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_apellidoCliente)
                            .addComponent(jTextField_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_agregarCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel_telefonoCliente)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_cancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_emailCliente)
                                    .addComponent(jTextField_emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_id_Cliente)
                            .addComponent(jTextField_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_nombreCliente)
                            .addComponent(jTextField_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_direccionCliente))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_id_Cliente)
                    .addComponent(jLabel_nombreCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_nombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_telefonoCliente)
                    .addComponent(jLabel_apellidoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_apellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_telefonoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_direccionCliente)
                    .addComponent(jLabel_emailCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_direccionCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_emailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_agregarCliente)
                    .addComponent(jButton_cancelarCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPanelClientes.addTab("Registro de clientes", jPanel6);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPanelClientes.addTab("Pagos", jLabel6);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelClientes)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 986, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPanePrincipal.addTab("Clientes", jPanel3);

        jButton_Cliente.setBackground(new java.awt.Color(204, 204, 204));
        jButton_Cliente.setForeground(new java.awt.Color(70, 106, 124));
        jButton_Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/grupo (1).png"))); // NOI18N
        jButton_Cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Cliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPanePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //<editor-fold defaultstate="collapsed" desc="CODIGO DE CLIENTE">
    private void jButton_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ClienteActionPerformed
        jTabbedPanePrincipal.setSelectedIndex(1); //cuando presionamos a este metodo se le asigna el valor de 1, indicando que pasamos al tag1
        
    }//GEN-LAST:event_jButton_ClienteActionPerformed

    private void jTextField_emailClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_emailClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailClienteActionPerformed

    private void jButton_agregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_agregarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_agregarClienteActionPerformed

    private void jButton_cancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_cancelarClienteActionPerformed

    private void jTextField_direccionClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_direccionClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_direccionClienteActionPerformed

    private void jTextField_telefonoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_telefonoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoClienteActionPerformed

    private void jTextField_apellidoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_apellidoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellidoClienteActionPerformed

    private void jTextField_idClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_idClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idClienteActionPerformed

    private void jLabel_imagenClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_imagenClienteMouseClicked
        Objetos.cargarImagen.CargarImagen(jLabel_imagenCliente);
    }//GEN-LAST:event_jLabel_imagenClienteMouseClicked

    private void jTextField_idClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idClienteKeyReleased
        if (jTextField_idCliente.getText().equals("")) {
            jLabel_id_Cliente.setForeground(new Color(102,102,102));
        }else{
            jLabel_id_Cliente.setText("ID Cliente:");
            jLabel_id_Cliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_idClienteKeyReleased

    private void jTextField_idClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_idClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_idClienteKeyTyped

    private void jTextField_nombreClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreClienteKeyReleased
        if (jTextField_nombreCliente.getText().equals("")) {
            jLabel_nombreCliente.setForeground(new Color(102,102,102));
        }else{
            jLabel_nombreCliente.setText("Nombre:");
            jLabel_nombreCliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_nombreClienteKeyReleased

    private void jTextField_nombreClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_nombreClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_nombreClienteKeyTyped

    private void jTextField_apellidoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_apellidoClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_apellidoClienteKeyTyped

    private void jTextField_apellidoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_apellidoClienteKeyReleased
          if (jTextField_apellidoCliente.getText().equals("")) {
            jLabel_apellidoCliente.setForeground(new Color(102,102,102));
        }else{
            jLabel_apellidoCliente.setText("Apellido Paterno:");
            jLabel_apellidoCliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_apellidoClienteKeyReleased

    private void jTextField_telefonoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonoClienteKeyReleased
        if (jTextField_telefonoCliente.getText().equals("")) {
            jLabel_telefonoCliente.setForeground(new Color(102,102,102));
        }else{
            jLabel_telefonoCliente.setText("Telefono:");
            jLabel_telefonoCliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_telefonoClienteKeyReleased

    private void jTextField_telefonoClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_telefonoClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_telefonoClienteKeyTyped

    private void jTextField_direccionClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_direccionClienteKeyReleased
        if (jTextField_direccionCliente.getText().equals("")) {
            jLabel_direccionCliente.setForeground(new Color(102,102,102));
        }else{
            jLabel_direccionCliente.setText("Dirección:");
            jLabel_direccionCliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_direccionClienteKeyReleased

    private void jTextField_direccionClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_direccionClienteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_direccionClienteKeyTyped

    private void jTextField_emailClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_emailClienteKeyReleased
        if (jTextField_emailCliente.getText().equals("")) {
            jLabel_emailCliente.setForeground(new Color(102,102,102));
        }else{
            jLabel_emailCliente.setText("e-mail:");
            jLabel_emailCliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_jTextField_emailClienteKeyReleased
    //</editor-fold>
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JButton jButton_Cliente;
    private javax.swing.JButton jButton_agregarCliente;
    private javax.swing.JButton jButton_cancelarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_apellidoCliente;
    private javax.swing.JLabel jLabel_direccionCliente;
    private javax.swing.JLabel jLabel_emailCliente;
    private javax.swing.JLabel jLabel_id_Cliente;
    private javax.swing.JLabel jLabel_imagenCliente;
    private javax.swing.JLabel jLabel_nombreCliente;
    private javax.swing.JLabel jLabel_telefonoCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPanePrincipal;
    private javax.swing.JTabbedPane jTabbedPanelClientes;
    private javax.swing.JTextField jTextField_BuscarCliente;
    private javax.swing.JTextField jTextField_apellidoCliente;
    private javax.swing.JTextField jTextField_direccionCliente;
    private javax.swing.JTextField jTextField_emailCliente;
    private javax.swing.JTextField jTextField_idCliente;
    private javax.swing.JTextField jTextField_nombreCliente;
    private javax.swing.JTextField jTextField_telefonoCliente;
    // End of variables declaration//GEN-END:variables
}
